const sampleData = [
  {
    hackathonName: "Hack the Future",
    hackathonDate: new Date("2025-02-15"),
    hackathonLocation: "virtual",
    projectTitle: "Smart Traffic Management",
    problemStatement: "Traffic congestion leads to increased travel time and pollution.",
    solution: "An AI-based system that optimizes traffic light cycles in real-time.",
    technologies: ["Node.js", "Express", "MongoDB", "TensorFlow"],
    challenges: "Integrating live traffic APIs was difficult.",
    learnings: "Improved knowledge of AI in real-time systems.",
    teamMembers: ["Alice", "Bob", "Charlie"],
    projectLink: "https://github.com/team/smart-traffic",
    images: ["https://example.com/images/traffic1.png", "https://example.com/images/traffic2.png"],
  },
  {
    hackathonName: "CodeStorm 2025",
    hackathonDate: new Date("2025-03-20"),
    hackathonLocation: "physical",
    projectTitle: "EcoCart",
    problemStatement: "People struggle to track their carbon footprint while shopping.",
    solution: "An e-commerce plugin that shows the carbon footprint of each product.",
    technologies: ["React", "Node.js", "MongoDB"],
    challenges: "Collecting accurate carbon footprint data.",
    learnings: "Learned about sustainable computing practices.",
    teamMembers: ["David", "Eva"],
    projectLink: "https://github.com/team/ecocart",
    images: ["https://example.com/images/ecocart1.png"],
  },
  {
    hackathonName: "HealthTech Hackathon",
    hackathonDate: new Date("2024-11-10"),
    hackathonLocation: "virtual",
    projectTitle: "MediConnect",
    problemStatement: "Patients face difficulty sharing medical reports across hospitals.",
    solution: "A blockchain-based platform for secure medical record sharing.",
    technologies: ["Ethereum", "Solidity", "React"],
    challenges: "Gas fees on blockchain were high.",
    learnings: "Learned about blockchain security.",
    teamMembers: ["Sophia", "Liam", "Olivia"],
    projectLink: "https://github.com/team/mediconnect",
    images: ["https://example.com/images/mediconnect1.png", "https://example.com/images/mediconnect2.png"],
  },
  {
    hackathonName: "AI Innovators",
    hackathonDate: new Date("2025-01-05"),
    hackathonLocation: "physical",
    projectTitle: "FarmAI",
    problemStatement: "Farmers struggle with crop disease detection.",
    solution: "AI-powered app to detect crop diseases from leaf images.",
    technologies: ["Python", "TensorFlow", "Flask"],
    challenges: "Building dataset for local crops was hard.",
    learnings: "Learned image classification techniques.",
    teamMembers: ["Noah", "Emma"],
    projectLink: "https://github.com/team/farmAI",
    images: ["https://example.com/images/farm1.png"],
  },
  {
    hackathonName: "FinTech Fest",
    hackathonDate: new Date("2025-04-01"),
    hackathonLocation: "virtual",
    projectTitle: "Budget Buddy",
    problemStatement: "Young professionals struggle with managing expenses.",
    solution: "Mobile app for AI-based personal budgeting and savings tips.",
    technologies: ["React Native", "Firebase", "Node.js"],
    challenges: "Synchronizing across devices was tricky.",
    learnings: "Learned about mobile-first design.",
    teamMembers: ["Ava", "Mason"],
    projectLink: "https://github.com/team/budgetbuddy",
    images: ["https://example.com/images/budget1.png", "https://example.com/images/budget2.png"],
  },
  {
    hackathonName: "Smart City Challenge",
    hackathonDate: new Date("2024-12-18"),
    hackathonLocation: "physical",
    projectTitle: "GreenBin",
    problemStatement: "Waste segregation is not efficient in many cities.",
    solution: "IoT-enabled smart bins that detect and sort waste.",
    technologies: ["Arduino", "Python", "MQTT"],
    challenges: "Hardware integration was time-consuming.",
    learnings: "Hands-on experience with IoT protocols.",
    teamMembers: ["Lucas", "Mia", "James"],
    projectLink: "https://github.com/team/greenbin",
    images: ["https://example.com/images/greenbin1.png"],
  },
  {
    hackathonName: "EdTech Hack",
    hackathonDate: new Date("2025-06-22"),
    hackathonLocation: "virtual",
    projectTitle: "LearnAR",
    problemStatement: "Students find it difficult to visualize complex science concepts.",
    solution: "An AR app for interactive 3D learning.",
    technologies: ["Unity", "C#", "ARCore"],
    challenges: "Device compatibility issues.",
    learnings: "Learned AR app development.",
    teamMembers: ["Isabella", "Ethan"],
    projectLink: "https://github.com/team/learnar",
    images: ["https://example.com/images/learnar1.png", "https://example.com/images/learnar2.png"],
  },
  {
    hackathonName: "CyberSec Hackathon",
    hackathonDate: new Date("2025-05-12"),
    hackathonLocation: "physical",
    projectTitle: "PhishGuard",
    problemStatement: "Phishing emails trick many users into sharing personal info.",
    solution: "AI-based browser plugin to detect phishing emails and links.",
    technologies: ["Python", "Flask", "Scikit-learn"],
    challenges: "Detecting zero-day phishing attacks.",
    learnings: "Improved skills in machine learning security.",
    teamMembers: ["Charlotte", "Benjamin"],
    projectLink: "https://github.com/team/phishguard",
    images: ["https://example.com/images/phish1.png"],
  },
  {
    hackathonName: "Green Energy Hack",
    hackathonDate: new Date("2025-07-08"),
    hackathonLocation: "virtual",
    projectTitle: "SolarOptimizer",
    problemStatement: "Solar panels lose efficiency due to poor placement.",
    solution: "ML model to suggest optimal placement for solar panels.",
    technologies: ["Python", "Scikit-learn", "Django"],
    challenges: "Lack of real-world solar panel data.",
    learnings: "Worked with regression models.",
    teamMembers: ["Harper", "Elijah"],
    projectLink: "https://github.com/team/solaroptimizer",
    images: ["https://example.com/images/solar1.png", "https://example.com/images/solar2.png"],
  },
  {
    hackathonName: "Women in Tech Hackathon",
    hackathonDate: new Date("2025-03-28"),
    hackathonLocation: "physical",
    projectTitle: "SafeWalk",
    problemStatement: "Many women feel unsafe walking alone at night.",
    solution: "A mobile app with real-time tracking and emergency alerts.",
    technologies: ["React Native", "Firebase", "Google Maps API"],
    challenges: "Implementing reliable location tracking.",
    learnings: "Learned about mobile security best practices.",
    teamMembers: ["Amelia", "Henry", "Ella"],
    projectLink: "https://github.com/team/safewalk",
    images: ["https://example.com/images/safewalk1.png"],
  }
];

module.exports = { data: sampleData };
