const sampleHackathons = [
  {
    name: "Hack the Future",
    description: "A global hackathon focusing on AI, blockchain, and sustainable tech solutions.",
    organizer: "TechWorld Inc.",
    startDate: new Date("2025-11-10"),
    endDate: new Date("2025-11-12"),
    registrationDeadline: new Date("2025-11-05"),
    location: "San Francisco, USA",
    registrationLink: "https://hackthefuture.com/register",
    image: "hackfuture.jpg",
    tags: ["AI", "Blockchain", "Sustainability"],
    status: "upcoming",
    createdBy: "652f1a9e9b8c1a7d1f9c1234",
  },
  {
    name: "CodeSprint 2025",
    description: "A 24-hour coding sprint for solving real-world industry challenges.",
    organizer: "DevHub",
    startDate: new Date("2025-12-01"),
    endDate: new Date("2025-12-02"),
    registrationDeadline: new Date("2025-11-25"),
    location: "Virtual",
    registrationLink: "https://codesprint.dev/register",
    image: "codesprint.png",
    tags: ["Web", "Cloud", "IoT"],
    status: "upcoming",
    createdBy: "652f1a9e9b8c1a7d1f9c5678",
  },
  {
    name: "Hack for Earth",
    description: "A hackathon dedicated to creating solutions for climate change and green energy.",
    organizer: "GreenTech Foundation",
    startDate: new Date("2025-09-01"),
    endDate: new Date("2025-09-03"),
    registrationDeadline: new Date("2025-08-25"),
    location: "Berlin, Germany",
    registrationLink: "https://hackforearth.org/apply",
    image: "hackearth.jpg",
    tags: ["Climate", "Energy", "Sustainability"],
    status: "completed",
    createdBy: "652f1a9e9b8c1a7d1f9c9101",
  },
  {
    name: "AI Innovators Hack",
    description: "Build innovative AI models that push the limits of creativity and automation.",
    organizer: "OpenAI Students Club",
    startDate: new Date("2025-10-15"),
    endDate: new Date("2025-10-17"),
    registrationDeadline: new Date("2025-10-10"),
    location: "Boston, USA",
    registrationLink: "https://aiinnovatorshack.io/signup",
    image: "aihack.png",
    tags: ["AI", "ML", "Data Science"],
    status: "ongoing",
    createdBy: "652f1a9e9b8c1a7d1f9c4321",
  },
  {
    name: "FinTech Hackathon",
    description: "A hackathon for designing modern banking, crypto, and payment solutions.",
    organizer: "FinTech Alliance",
    startDate: new Date("2025-11-20"),
    endDate: new Date("2025-11-22"),
    registrationDeadline: new Date("2025-11-15"),
    location: "London, UK",
    registrationLink: "https://fintechhack.com/join",
    image: "fintech.png",
    tags: ["Finance", "Blockchain", "Payments"],
    status: "upcoming",
    createdBy: "652f1a9e9b8c1a7d1f9c8765",
  },
  {
    name: "HealthHack 2025",
    description: "Innovating healthcare solutions with AI, wearable tech, and IoT devices.",
    organizer: "MediTech Labs",
    startDate: new Date("2025-08-05"),
    endDate: new Date("2025-08-07"),
    registrationDeadline: new Date("2025-07-31"),
    location: "New Delhi, India",
    registrationLink: "https://healthhack.org/register",
    image: "healthhack.jpg",
    tags: ["Healthcare", "IoT", "AI"],
    status: "completed",
    createdBy: "652f1a9e9b8c1a7d1f9c6789",
  },
  {
    name: "CyberSec Challenge",
    description: "A hackathon to solve real-world cybersecurity threats and digital forensics tasks.",
    organizer: "CyberSecure",
    startDate: new Date("2025-12-15"),
    endDate: new Date("2025-12-17"),
    registrationDeadline: new Date("2025-12-10"),
    location: "Singapore",
    registrationLink: "https://cybersecchallenge.com/register",
    image: "cybersec.png",
    tags: ["Cybersecurity", "Forensics", "Ethical Hacking"],
    status: "upcoming",
    createdBy: "652f1a9e9b8c1a7d1f9c4322",
  },
  {
    name: "AgriTech Hackathon",
    description: "Solving agricultural problems with smart technology, sensors, and AI.",
    organizer: "FarmTech Solutions",
    startDate: new Date("2025-10-01"),
    endDate: new Date("2025-10-03"),
    registrationDeadline: new Date("2025-09-27"),
    location: "Nairobi, Kenya",
    registrationLink: "https://agritechhack.com/signup",
    image: "agritech.jpg",
    tags: ["Agriculture", "IoT", "AI"],
    status: "completed",
    createdBy: "652f1a9e9b8c1a7d1f9c1357",
  },
  {
    name: "Women in Tech Hack",
    description: "Encouraging women developers to build innovative solutions across industries.",
    organizer: "WiT Foundation",
    startDate: new Date("2025-11-05"),
    endDate: new Date("2025-11-06"),
    registrationDeadline: new Date("2025-11-01"),
    location: "Virtual",
    registrationLink: "https://wit-hackathon.com/join",
    image: "wit.png",
    tags: ["Women", "Diversity", "Innovation"],
    status: "upcoming",
    createdBy: "652f1a9e9b8c1a7d1f9c9988",
  },
  {
    name: "SpaceTech Hackathon",
    description: "Innovating space exploration and satellite communication systems.",
    organizer: "NASA Student Chapter",
    startDate: new Date("2025-07-15"),
    endDate: new Date("2025-07-17"),
    registrationDeadline: new Date("2025-07-10"),
    location: "Houston, USA",
    registrationLink: "https://spacetechhack.org/apply",
    image: "spacetech.jpg",
    tags: ["Space", "Satellite", "Exploration"],
    status: "completed",
    createdBy: "652f1a9e9b8c1a7d1f9c5432",
  },
];



module.exports = { data: sampleHackathons };